/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings.$bookingId'
import { Route as StationsIndexRouteImport } from './routes/stations.index'
import { Route as StationsStationIdRouteImport } from './routes/stations.$stationId'
import { Route as AdminBookingsIndexRouteImport } from './routes/admin.bookings.index'
import { Route as AdminBookingsBookingIdRouteImport } from './routes/admin.bookings.$bookingId'
import { Route as AdminStationsIndexRouteImport } from './routes/admin.stations.index'
import { Route as AdminStationsNewRouteImport } from './routes/admin.stations.new'
import { Route as AdminStationsStationIdSlotsRouteImport } from './routes/admin.stations.$stationId.slots'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsIndexRoute = StationsIndexRouteImport.update({
  id: '/stations/',
  path: '/stations/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsStationIdRoute = StationsStationIdRouteImport.update({
  id: '/stations/$stationId',
  path: '/stations/$stationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/admin/bookings/',
  path: '/admin/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsBookingIdRoute = AdminBookingsBookingIdRouteImport.update({
  id: '/admin/bookings/$bookingId',
  path: '/admin/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStationsIndexRoute = AdminStationsIndexRouteImport.update({
  id: '/admin/stations/',
  path: '/admin/stations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStationsNewRoute = AdminStationsNewRouteImport.update({
  id: '/admin/stations/new',
  path: '/admin/stations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStationsStationIdSlotsRoute =
  AdminStationsStationIdSlotsRouteImport.update({
    id: '/admin/stations/$stationId/slots',
    path: '/admin/stations/$stationId/slots',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/stations/$stationId': typeof StationsStationIdRoute
  '/bookings/': typeof BookingsIndexRoute
  '/stations/': typeof StationsIndexRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/stations/new': typeof AdminStationsNewRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/stations/': typeof AdminStationsIndexRoute
  '/admin/stations/$stationId/slots': typeof AdminStationsStationIdSlotsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/stations/$stationId': typeof StationsStationIdRoute
  '/bookings': typeof BookingsIndexRoute
  '/stations': typeof StationsIndexRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/stations/new': typeof AdminStationsNewRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/admin/stations': typeof AdminStationsIndexRoute
  '/admin/stations/$stationId/slots': typeof AdminStationsStationIdSlotsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/stations/$stationId': typeof StationsStationIdRoute
  '/bookings/': typeof BookingsIndexRoute
  '/stations/': typeof StationsIndexRoute
  '/admin/bookings/$bookingId': typeof AdminBookingsBookingIdRoute
  '/admin/stations/new': typeof AdminStationsNewRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/stations/': typeof AdminStationsIndexRoute
  '/admin/stations/$stationId/slots': typeof AdminStationsStationIdSlotsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/register'
    | '/bookings/$bookingId'
    | '/stations/$stationId'
    | '/bookings/'
    | '/stations/'
    | '/admin/bookings/$bookingId'
    | '/admin/stations/new'
    | '/admin/bookings/'
    | '/admin/stations/'
    | '/admin/stations/$stationId/slots'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/register'
    | '/bookings/$bookingId'
    | '/stations/$stationId'
    | '/bookings'
    | '/stations'
    | '/admin/bookings/$bookingId'
    | '/admin/stations/new'
    | '/admin/bookings'
    | '/admin/stations'
    | '/admin/stations/$stationId/slots'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/register'
    | '/bookings/$bookingId'
    | '/stations/$stationId'
    | '/bookings/'
    | '/stations/'
    | '/admin/bookings/$bookingId'
    | '/admin/stations/new'
    | '/admin/bookings/'
    | '/admin/stations/'
    | '/admin/stations/$stationId/slots'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  BookingsBookingIdRoute: typeof BookingsBookingIdRoute
  StationsStationIdRoute: typeof StationsStationIdRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  StationsIndexRoute: typeof StationsIndexRoute
  AdminBookingsBookingIdRoute: typeof AdminBookingsBookingIdRoute
  AdminStationsNewRoute: typeof AdminStationsNewRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
  AdminStationsIndexRoute: typeof AdminStationsIndexRoute
  AdminStationsStationIdSlotsRoute: typeof AdminStationsStationIdSlotsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations/': {
      id: '/stations/'
      path: '/stations'
      fullPath: '/stations/'
      preLoaderRoute: typeof StationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations/$stationId': {
      id: '/stations/$stationId'
      path: '/stations/$stationId'
      fullPath: '/stations/$stationId'
      preLoaderRoute: typeof StationsStationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings/': {
      id: '/admin/bookings/'
      path: '/admin/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings/$bookingId': {
      id: '/admin/bookings/$bookingId'
      path: '/admin/bookings/$bookingId'
      fullPath: '/admin/bookings/$bookingId'
      preLoaderRoute: typeof AdminBookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stations/': {
      id: '/admin/stations/'
      path: '/admin/stations'
      fullPath: '/admin/stations/'
      preLoaderRoute: typeof AdminStationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stations/new': {
      id: '/admin/stations/new'
      path: '/admin/stations/new'
      fullPath: '/admin/stations/new'
      preLoaderRoute: typeof AdminStationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stations/$stationId/slots': {
      id: '/admin/stations/$stationId/slots'
      path: '/admin/stations/$stationId/slots'
      fullPath: '/admin/stations/$stationId/slots'
      preLoaderRoute: typeof AdminStationsStationIdSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  BookingsBookingIdRoute: BookingsBookingIdRoute,
  StationsStationIdRoute: StationsStationIdRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  StationsIndexRoute: StationsIndexRoute,
  AdminBookingsBookingIdRoute: AdminBookingsBookingIdRoute,
  AdminStationsNewRoute: AdminStationsNewRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
  AdminStationsIndexRoute: AdminStationsIndexRoute,
  AdminStationsStationIdSlotsRoute: AdminStationsStationIdSlotsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
